services:
  server:
    build:
      context: ./${BACK_DIR}
    image: ${TAG}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    environment:
      - PORT=${PORT}
    networks:
      - calate_net

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - calate_net

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - calate_net

volumes:
  pgdata:

networks:
  calate_net:
    driver: bridge
