FROM golang:1.24
WORKDIR /app

ARG APPNAME

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o ../output/APPNAME

#EXPOSE not included, port binding is passed at runtime to the docker command, check makefile

ENTRYPOINT [ "output/APPNAME" ]
